version: "2"
services:
  runner:
    image: teikitu-github-runner-win:latest
    cpus: 0.5
    build:
      context: .
      args:
        RUNNER_VERSION: '2.321.0'
    environment:
      GH_OWNER_ENV: ${GH_OWNER}
      GH_TOKEN_ENV: ${GH_TOKEN}
      GH_REPOSITORY: ${GH_REPOSITORY}
