# escape=`

# Use the latest Windows Server Core 2025 image.
FROM --platform=linux/amd64 ubuntu:24.04

# Input GitHub runner version argument
ARG RUNNER_VERSION
ENV DEBIAN_FRONTEND=noninteractive

# Additional label information
LABEL Author="Andrew Aye"
LABEL Email="github.sublime362@passmail.net"
LABEL GitHub="https://github.com/teikitu/teikitu-release"
LABEL BaseImage="ubuntu:24.04"
LABEL RunnerVersion=${RUNNER_VERSION}

# update the base packages + add a non-sudo user
RUN apt-get update -y && apt-get upgrade -y && useradd -m docker

# Install dependenciesls -al
RUN apt-get install -y --no-install-recommends lsb-release
RUN apt-get install -y --no-install-recommends wget
RUN apt-get install -y --no-install-recommends unzip
RUN apt-get install -y --no-install-recommends jq
RUN apt-get install -y --no-install-recommends libssl-dev
RUN apt-get install -y --no-install-recommends gpg
RUN apt-get install -y --no-install-recommends gnupg
RUN apt-get install -y --no-install-recommends software-properties-common
RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential

# Development tools - LLVM (installs package repo for other dev tools as well)
RUN wget --no-check-certificate https://apt.llvm.org/llvm.sh `
    && chmod +x ./llvm.sh `
    && ./llvm.sh 19 all `
    && rm llvm.sh
RUN apt-get update
RUN apt-get install -y --no-install-recommends ninja-build
RUN apt-get install -y --no-install-recommends nodejs
RUN apt-get install -y --no-install-recommends libcurl4-openssl-dev

# Powershell
RUN wget https://github.com/PowerShell/PowerShell/releases/download/v7.4.6/powershell_7.4.6-1.deb_amd64.deb `
    && dpkg -i powershell_7.4.6-1.deb_amd64.deb `
    && apt-get install -f `
    && rm powershell_7.4.6-1.deb_amd64.deb

# GitHub CLI
RUN apt-get install -y --no-install-recommends gh

# CMake
RUN apt-get install -y --no-install-recommends libtool
RUN apt-get install -y --no-install-recommends autoconf
RUN apt remove --purge --auto-remove cmake
RUN version=3.31 `
    && build=2 `
    && mkdir ~/temp `
    && cd ~/temp `
    && wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz `
    && tar -xzvf cmake-$version.$build.tar.gz `
    && cd cmake-$version.$build/ `
    && export C=/usr/bin/clang-19 `
    && export CXX=/usr/bin/clang++-19 `
    && ./bootstrap `
    && make -j$(nproc) `
    && make install `
    && cd ~ `
    && rm -rf temp

# Install Python
RUN apt-get install -y --no-install-recommends python3
RUN apt-get install -y --no-install-recommends python3-pip
RUN apt-get install -y --no-install-recommends libpython3-dev

# GLFW
RUN apt-get install -y --no-install-recommends doxygen
RUN apt-get install -y --no-install-recommends xorg-dev
RUN apt-get install -y --no-install-recommends libglu1-mesa-dev

# Dependencies for Doxygen
RUN apt-get install -y --no-install-recommends flex
RUN apt-get install -y --no-install-recommends bison
RUN apt-get install -y --no-install-recommends libedit-dev
RUN apt-get install -y --no-install-recommends openjdk-21-jdk

# Boost

# Install Python dependencies needed for OpenUSD
RUN pip3 install Jinja2 --break-system-packages
RUN pip3 install PyOpenGL --break-system-packages
RUN pip3 install pyside6 --break-system-packages

# Action Runner dependencies
RUN wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh `
    && chmod +x ./dotnet-install.sh `
    && ./dotnet-install.sh --version latest `
    && rm dotnet-install.sh
RUN apt-get install -y --no-install-recommends liblttng-ust1
RUN apt-get install -y --no-install-recommends curl

# cd into the user directory, download and unzip the github actions runner
RUN cd /home/docker && mkdir actions-runner && cd actions-runner `
    && curl -O -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz `
    && tar xzf ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz

# install some additional dependencies
RUN chown -R docker ~docker && /home/docker/actions-runner/bin/installdependencies.sh
RUN apt-get install -y --no-install-recommends git

# add over the start.sh script
ADD start.sh start.sh

# make the script executable
RUN chmod +x start.sh

# set the user to "docker" so all subsequent commands are run as the docker user
USER docker

# set the entrypoint to the start.sh script
ENTRYPOINT ["./start.sh"]
